name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: gradle:8.4-jdk2

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: ./gradlew jib
